### ISSUE TITLE
colour mismatch

### ISSUE THREAD

**Issue by KevindeB93** [jamesy012/OpenPlanet-BestCheckpoints#11]
Hi james,

It is me again. This time with an issue that should be a lot easier than the previous one.

It is not an issue really but just a small thing of..... AARGH.

Have you observed that the two colour greens are not the same? Or is it meant to have a little shade difference.
Anyhow, I thought it was a good one to inform you about it. So just some cosmetics this time haha.

Keep it up with the plug-in!

![image](https://user-images.githubusercontent.com/99325198/158257054-f511cf1e-eb25-4a84-9202-5a422c9258e0.png)

**Comment by KevindeB93** [comment]
OK. I think it was just me not recognizing it. When i did a small improvement of -0.003 it was the same colour green. I dont know if it is preferred by many. But uhm.... rather see this as a little feedback than haha!

**Comment by jamesy012** [comment]
lol glad your still using it
yeah just a random thing I did to the colours, should have added a toggle to turn it off
I wanted to get the numbers closer to 0 to be lighter since they aren't as significant 

I'll add in a way to disable the color blending but the next update on openplanet probably wont be for a while
