### ISSUE TITLE
Plugin breaks on Up & Down ft proof_ TOTD map (6th of July 2022)

### ISSUE THREAD

**Issue by Atheuz** [jamesy012/OpenPlanet-BestCheckpoints#20]
Map: https://trackmania.io/#/totd/leaderboard/7dfd31de-bf3d-41be-b17f-fa3861d4ff50/mlikgNqQTxsjBXyB7L46fdq0bkg
If you play this map, the plugin will seemingly get stuck in a recording state and cease to function on all maps until you restart the game or the plugin.

Steps to reproduce:
1) Open the map from above.
2) Play a round
3) Observe state: 
![billede](https://user-images.githubusercontent.com/202696/177612699-c2fae996-1850-470c-8ab3-37e6d1f9afea.png)
4) See that the state follows you as you go to other maps:
![billede](https://user-images.githubusercontent.com/202696/177612745-0bd00340-a5d7-4bc9-96cc-40de9211fd57.png)

It's likely to do with the fact that it's a multilap map, that doesn't end in the multilap gate but instead in a separate finish gate.

**Comment by jamesy012** [comment]
Thanks for alerting me, dont play as much these days so probably wouldn't have noticed
the map was just causing the plugin to crash which is why the times stuck around for other maps

I put out a new update if you want to try again and see if it's actually resolved for you (if you could close the issue afterwards that would be great)
The map does cause some issues still and doesnt match what the plugin should be doing but it's close enough

**Comment by Atheuz** [comment]
Doesn't break the plugin anymore, but it still doesn't really work on the map. It's fine I guess.
